Initial golang multi buildpack
Signed-off-by: Dave Goddard <dave@goddard.id.au>
Signed-off-by: Sam Smith <sesmith177@gmail.com>

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,17 +1,40 @@
-#!/usr/bin/env ruby
+#!/bin/bash
+set -euo pipefail
 
-$stdout.sync = true
-$stderr.sync = true
-$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
+BUILD_DIR=$1
+CACHE_DIR=$2
+export BUILDPACK_DIR=`dirname $(readlink -f ${BASH_SOURCE%/*})`
 
-require 'multi_buildpack_stager'
+GO_VERSION="1.7.5"
+GO_MD5="c9de5bb95790044de676301898e92a1b"
 
-build_dir = ARGV[0]
-cache_dir = ARGV[1]
-buildpack_dir = File.join(File.dirname(__FILE__), '..')
+URL=https://buildpacks.cloudfoundry.org/dependencies/go/go${GO_VERSION}.linux-amd64-c9de5bb9.tar.gz
 
-version = File.read(File.join(buildpack_dir, 'VERSION')).strip
-puts "-----> Buildpack version #{version}"
+echo "-----> Download go ${GO_VERSION}"
+curl -s -L --retry 15 --retry-delay 2 $URL -o /tmp/go.tar.gz
 
-stager = MultiBuildpackStager.new(build_dir, cache_dir)
-stager.run!
+DOWNLOAD_MD5=$(md5sum /tmp/go.tar.gz | cut -d ' ' -f 1)
+
+if [[ $DOWNLOAD_MD5 != $GO_MD5 ]]; then
+  echo "       **ERROR** MD5 mismatch: got $DOWNLOAD_MD5 expected $GO_MD5"
+  exit 1
+fi
+
+tar xzf /tmp/go.tar.gz -C /tmp
+
+export GOROOT=/tmp/go
+export GOPATH=$BUILDPACK_DIR
+
+if [ -f $GOROOT/bin/go ]; then
+  echo "-----> Running go build compile"
+  output_dir=$(mktemp -d -t compileXXX)
+  $GOROOT/bin/go build -o $output_dir/compile compile
+else
+  echo "       **ERROR** Could not download go"
+  exit 1
+fi
+
+unset GOROOT
+unset GOPATH
+
+$output_dir/compile $BUILD_DIR $CACHE_DIR
